#!/usr/bin/env ruby
# frozen_string_literal: true

# Mac Developer Context Generator
# Injects 750+ lines of Mac-specific knowledge into Claude's context
#
# Usage: ./scripts/mac_context.rb
#        Creates .claude/mac_context.md
#
# Part of SaneProcess - The Supervisor for Claude Code
# "Your AI Developer is drunk. Here is the Supervisor."
#
# https://github.com/stephanjoseph/SaneProcess

require 'fileutils'

CONTEXT_FILE = '.claude/mac_context.md'

def generate_mac_context
  <<~CONTEXT
    # Mac Development Context

    > **CRITICAL**: This context is auto-generated by SaneProcess.
    > Claude MUST follow these patterns. Deviation = supervised hallucination.

    ---

    ## Build System Rules

    ### NEVER Touch .xcodeproj Directly
    - `.xcodeproj` files are binary XML - AI edits break them
    - Use `project.yml` + `xcodegen generate` instead
    - After creating new Swift files: ALWAYS run `xcodegen generate`

    ### Build Commands
    ```bash
    # RIGHT - Use project tools
    ./Scripts/build.rb verify

    # WRONG - Raw xcodebuild (misses configuration)
    xcodebuild -scheme MyApp build
    ```

    ### DerivedData Location
    - Build products: `~/Library/Developer/Xcode/DerivedData/<Project>-*/Build/Products/Debug/`
    - Clean with: `rm -rf ~/Library/Developer/Xcode/DerivedData/<Project>-*`

    ---

    ## Info.plist Patterns

    ### Required Keys (macOS App)
    ```xml
    <key>CFBundleIdentifier</key>
    <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>

    <key>CFBundleName</key>
    <string>$(PRODUCT_NAME)</string>

    <key>CFBundleVersion</key>
    <string>$(CURRENT_PROJECT_VERSION)</string>

    <key>CFBundleShortVersionString</key>
    <string>$(MARKETING_VERSION)</string>

    <key>LSMinimumSystemVersion</key>
    <string>$(MACOSX_DEPLOYMENT_TARGET)</string>

    <key>NSHumanReadableCopyright</key>
    <string>Copyright © 2026. All rights reserved.</string>
    ```

    ### Common Permission Keys
    | Permission | Key | When Needed |
    |------------|-----|-------------|
    | Camera | `NSCameraUsageDescription` | Recording video |
    | Microphone | `NSMicrophoneUsageDescription` | Recording audio |
    | Screen Recording | `NSScreenCaptureUsageDescription` | Screen capture |
    | Accessibility | `NSAccessibilityUsageDescription` | AX API access |
    | Location | `NSLocationUsageDescription` | Location services |
    | Contacts | `NSContactsUsageDescription` | Contacts access |
    | Photos | `NSPhotoLibraryUsageDescription` | Photo library |

    ---

    ## Entitlements

    ### Non-Sandboxed App (Development)
    ```xml
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "...">
    <plist version="1.0">
    <dict>
        <key>com.apple.security.app-sandbox</key>
        <false/>
    </dict>
    </plist>
    ```

    ### Sandboxed App (App Store)
    ```xml
    <key>com.apple.security.app-sandbox</key>
    <true/>

    <!-- Add capabilities as needed -->
    <key>com.apple.security.network.client</key>
    <true/>

    <key>com.apple.security.files.user-selected.read-write</key>
    <true/>
    ```

    ### Hardened Runtime (Notarization)
    ```xml
    <key>com.apple.security.hardened-runtime</key>
    <true/>

    <!-- If using JIT or unsigned code -->
    <key>com.apple.security.cs.allow-jit</key>
    <true/>

    <!-- If loading plugins -->
    <key>com.apple.security.cs.disable-library-validation</key>
    <true/>
    ```

    ---

    ## Sandboxing Gotchas

    ### File Access
    - Sandboxed apps can ONLY access:
      - App container: `~/Library/Containers/<bundle-id>/`
      - User-selected files (via NSOpenPanel)
      - Bookmarked URLs (security-scoped)
    - To access arbitrary files: Use `NSOpenPanel` + security-scoped bookmarks

    ### Security-Scoped Bookmarks
    ```swift
    // Save bookmark (after user selects file)
    let bookmarkData = try url.bookmarkData(
        options: .withSecurityScope,
        includingResourceValuesForKeys: nil,
        relativeTo: nil
    )
    UserDefaults.standard.set(bookmarkData, forKey: "savedBookmark")

    // Restore bookmark (on next launch)
    guard let data = UserDefaults.standard.data(forKey: "savedBookmark") else { return }
    var isStale = false
    let url = try URL(
        resolvingBookmarkData: data,
        options: .withSecurityScope,
        relativeTo: nil,
        bookmarkDataIsStale: &isStale
    )

    // CRITICAL: Start/stop access scope
    guard url.startAccessingSecurityScopedResource() else { return }
    defer { url.stopAccessingSecurityScopedResource() }

    // Now you can read/write the file
    let contents = try Data(contentsOf: url)
    ```

    ### Network Access
    - Requires entitlement: `com.apple.security.network.client`
    - Incoming connections: `com.apple.security.network.server`

    ### Temporary Files
    - Use `FileManager.default.temporaryDirectory` (inside container)
    - NOT `/tmp/` (outside sandbox)

    ---

    ## Notarization Requirements

    ### Before Submitting
    1. Hardened Runtime enabled
    2. Code signed with Developer ID
    3. No unsigned libraries
    4. Timestamp included in signature

    ### Common Notarization Failures
    | Error | Fix |
    |-------|-----|
    | "The executable does not have the hardened runtime enabled" | Add hardened-runtime entitlement |
    | "The signature does not include a secure timestamp" | Add `--timestamp` to codesign |
    | "The executable contains unsigned code" | Sign all dylibs and frameworks |

    ---

    ## Common Crash Patterns

    ### Actor Isolation Crashes
    ```
    Symptom: dispatch_assert_queue_fail
    Cause: assumeIsolated in deinit
    Fix: Use nonisolated(unsafe) or remove assumeIsolated from deinit
    ```

    ### NULL Pointer (Object Deallocated)
    ```
    Symptom: SIGSEGV at address 0x0-0x1000
    Cause: Accessing deallocated object
    Fix: Add isActive guards, use TimelineView for animations
    ```

    ### Race Condition
    ```
    Symptom: objc_release crash, random SIGSEGV
    Cause: Multiple threads accessing same object
    Fix: Use actors, @MainActor, or locks
    ```

    ### Crash Address Analysis
    | Address Range | Likely Cause |
    |---------------|--------------|
    | 0x0 - 0x1000 | NULL pointer dereference |
    | 0x1000 - 0xFFFF | Small offset from NULL (struct member access) |
    | 0x7fff... | Stack corruption |
    | Large random hex | Use-after-free or heap corruption |

    ### Thread Analysis
    | Faulting Thread | Likely Issue |
    |-----------------|--------------|
    | Thread 0 | Main thread / UI state issue |
    | Thread N > 0 | Background / concurrency bug |
    | EXC_BREAKPOINT | Swift assertion or actor isolation |
    | EXC_BAD_ACCESS | Memory corruption or use-after-free |

    ### Symbolication
    ```bash
    # Find crash logs
    ls ~/Library/Logs/DiagnosticReports/*.ips

    # Symbolicate with atos
    atos -arch arm64 -o MyApp.app.dSYM/Contents/Resources/DWARF/MyApp -l 0x100000000 0x100001234

    # Or use Xcode
    # Window > Devices and Simulators > View Device Logs
    ```

    ---

    ## Menu Bar Apps

    ### NSStatusItem Setup
    ```swift
    let statusItem = NSStatusBar.system.statusItem(withLength: NSStatusItem.variableLength)
    statusItem.button?.image = NSImage(named: "MenuBarIcon")
    statusItem.button?.image?.isTemplate = true  // CRITICAL for dark mode
    ```

    ### Menu Bar Icon Requirements
    - Size: 18x18 points (36x36 @2x)
    - Format: Template image (single color, alpha channel)
    - Asset catalog: Include 1x and 2x versions

    ### NSMenu Target
    ```swift
    // CRITICAL: Set target or items appear disabled
    let item = NSMenuItem(title: "Action", action: #selector(doAction), keyEquivalent: "")
    item.target = self  // <-- Without this, menu item is grayed out
    menu.addItem(item)
    ```

    ---

    ## Accessibility API

    ### Checking Permission
    ```swift
    let trusted = AXIsProcessTrusted()
    // Returns false if not in System Settings > Privacy > Accessibility
    ```

    ### Requesting Permission
    ```swift
    let options = [kAXTrustedCheckOptionPrompt.takeRetainedValue(): true] as CFDictionary
    AXIsProcessTrustedWithOptions(options)
    // Opens System Settings automatically
    ```

    ### Opening System Settings
    ```swift
    // CORRECT - Use Process with bundle ID
    let process = Process()
    process.executableURL = URL(fileURLWithPath: "/usr/bin/open")
    process.arguments = ["-b", "com.apple.systempreferences",
        "x-apple.systempreferences:com.apple.settings.PrivacySecurity.extension?Privacy_Accessibility"]
    try process.run()

    // WRONG - NSWorkspace.open() may open browser instead
    ```

    ---

    ## Swift Concurrency

    ### @MainActor Rules
    - All UI code must be @MainActor
    - Published properties on ObservableObject: @MainActor
    - Don't use assumeIsolated in deinit

    ### Task Patterns
    ```swift
    // RIGHT - Flat task structure
    Task { @MainActor in
        let result = await fetchData()
        self.data = result
    }

    // WRONG - Nested tasks cause actor-hopping issues
    Task {
        Task { @MainActor in
            // Can freeze at _isSameExecutor
        }
    }
    ```

    ### Notification Handling (Swift 6)
    ```swift
    // RIGHT - Extract values before Task
    NotificationCenter.default.addObserver(forName: .didChange, object: nil, queue: .main) { notification in
        let value = notification.userInfo?["key"] as? String  // Extract here
        Task { @MainActor in
            self.handleChange(value)  // Use extracted value
        }
    }

    // WRONG - Notification object crosses actor boundary
    Task { @MainActor in
        let value = notification.userInfo?["key"]  // Sendable violation
    }
    ```

    ---

    ## Swift 6.2 Approachable Concurrency (WWDC 2025)

    ### New Build Setting
    ```
    SWIFT_UPCOMING_FEATURE_APPROACHABLE_CONCURRENCY = YES
    ```

    ### Key Changes
    - `nonisolated async` functions now run on caller's actor by default
    - Use `@concurrent` to explicitly run on background thread
    - Automatic `@Sendable` inference for method references
    - `isolated` deinitializers for actor-isolated classes

    ### Migration Pattern
    ```swift
    // Swift 6.0 - Explicit @Sendable everywhere
    let callback: @Sendable () -> Void = { ... }

    // Swift 6.2 - Automatic inference for Sendable types
    let callback = someObject.sendableMethod  // Inferred @Sendable
    ```

    ### Isolated Deinit (New)
    ```swift
    @MainActor
    class ViewController {
        isolated deinit {
            // Runs on MainActor, safe to access properties
            cleanup()
        }
    }
    ```

    ---

    ## Liquid Glass (macOS 26 / iOS 26)

    ### Core API
    ```swift
    // Basic glass effect
    Text("Hello")
        .glassEffect(.regular, in: .rect(cornerRadius: 16))

    // Interactive (responds to touch/pointer)
    Button("Tap Me") { }
        .glassEffect(.regular.interactive(), in: .capsule)

    // Built-in button styles
    Button("Action") { }
        .buttonStyle(.glass)           // Subtle
        .buttonStyle(.glassProminent)  // Bold
    ```

    ### Availability Gating (REQUIRED)
    ```swift
    if #available(macOS 26, iOS 26, *) {
        content.glassEffect(.regular, in: .rect(cornerRadius: 16))
    } else {
        content.background(.ultraThinMaterial, in: .rect(cornerRadius: 16))
    }
    ```

    ### Container Pattern
    ```swift
    GlassEffectContainer(spacing: 24) {
        // Child views get coordinated glass treatment
        CardView()
        CardView()
    }
    ```

    ### Morphing Transitions
    ```swift
    @Namespace var namespace

    // Source
    Image(systemName: "star")
        .glassEffectID("icon", in: namespace)

    // Destination
    Image(systemName: "star.fill")
        .glassEffectID("icon", in: namespace)
    ```

    ### One-Year Opt-Out
    Apps can disable Liquid Glass for one year by setting:
    ```
    UIDesignRequiresCompatibilityMode = YES  // Info.plist
    ```

    ---

    ## SwiftUI Performance Anti-Patterns

    ### Expensive Work in Body (BAD)
    ```swift
    // WRONG - Creates formatter on every render
    var body: some View {
        Text(NumberFormatter().string(from: value) ?? "")
    }

    // RIGHT - Cache formatter
    private static let formatter = NumberFormatter()
    var body: some View {
        Text(Self.formatter.string(from: value) ?? "")
    }
    ```

    ### Unstable Identity (BAD)
    ```swift
    // WRONG - UUID changes every render
    ForEach(items, id: \\.self) { item in ... }

    // RIGHT - Stable ID property
    ForEach(items, id: \\.id) { item in ... }
    ```

    ### Sorting in ForEach (BAD)
    ```swift
    // WRONG - Sorts on every body evaluation
    ForEach(items.sorted(by: { $0.date > $1.date })) { ... }

    // RIGHT - Pre-sort and store
    @State private var sortedItems: [Item] = []

    var body: some View {
        ForEach(sortedItems) { ... }
    }
    .onChange(of: items) { sortedItems = items.sorted(...) }
    ```

    ### Broad Observable (BAD)
    ```swift
    // WRONG - All views update when ANY property changes
    @Observable class AppState {
        var user: User
        var settings: Settings
        var cache: Cache
    }

    // RIGHT - Granular observables
    @Observable class UserState { var user: User }
    @Observable class SettingsState { var settings: Settings }
    ```

    ### Performance Audit Checklist
    - [ ] State as close to leaf views as possible?
    - [ ] ForEach identities stable and unique?
    - [ ] No formatters/sorting/filtering in body?
    - [ ] Images downsampled before render?
    - [ ] No implicit animations on large hierarchies?

    ---

    ## Foundation Models Framework (macOS 26+)

    ### On-Device LLM
    ```swift
    import FoundationModels

    let session = LanguageModelSession()
    let response = try await session.respond(to: "Summarize this text...")
    print(response.content)
    ```

    ### Key Points
    - Runs entirely on-device (no internet required)
    - No app size increase (models are system-provided)
    - Available on iOS 26, iPadOS 26, macOS 26, visionOS 26
    - Privacy-preserving (data never leaves device)

    ---

    ## WebView in SwiftUI (macOS 26+)

    ### Native WebView (Finally!)
    ```swift
    import SwiftUI
    import WebKit

    struct ContentView: View {
        var body: some View {
            WebView(url: URL(string: "https://apple.com")!)
        }
    }

    // No more WKWebView wrapping needed
    ```

    ### With Navigation
    ```swift
    @State private var url = URL(string: "https://apple.com")!

    var body: some View {
        VStack {
            WebView(url: url)
                .onNavigationAction { action in
                    // Handle navigation
                    return .allow
                }

            HStack {
                Button("Back") { /* webView.goBack() */ }
                Button("Forward") { /* webView.goForward() */ }
            }
        }
    }
    ```

    ---

    ## Chart3D (Swift Charts - macOS 26+)

    ### 3D Bar Chart
    ```swift
    import Charts

    Chart3D(data) { item in
        BarMark3D(
            x: .value("Category", item.category),
            y: .value("Value", item.value),
            z: .value("Series", item.series)
        )
    }
    .chartXAxisLabel("Categories")
    .chartYAxisLabel("Values")
    ```

    ### Interactive Rotation
    ```swift
    Chart3D(data) { ... }
        .chart3DRotation(pitch: .degrees(30), yaw: .degrees(45))
        .chart3DInteraction(.rotate)  // User can rotate
    ```

    ---

    ## App Intents + Spotlight (macOS 26+)

    ### Basic Intent
    ```swift
    import AppIntents

    struct OpenProjectIntent: AppIntent {
        static var title: LocalizedStringResource = "Open Project"
        static var description = IntentDescription("Opens a project in the app")

        @Parameter(title: "Project Name")
        var projectName: String

        func perform() async throws -> some IntentResult {
            // Open the project
            await ProjectManager.shared.open(projectName)
            return .result()
        }
    }
    ```

    ### Spotlight Surfacing
    App Intents are now automatically surfaced in Spotlight on macOS Tahoe.
    Users can type "Open Project MyApp" and Spotlight will suggest your intent.

    ```swift
    // Register in your App
    struct MyApp: App {
        var body: some Scene {
            WindowGroup { ContentView() }
        }

        init() {
            // Intents auto-register, but you can customize
            OpenProjectIntent.updateAppShortcutParameters()
        }
    }
    ```

    ---

    ## XcodeGen (project.yml)

    ### Minimal Template
    ```yaml
    name: MyApp
    options:
      bundleIdPrefix: com.company
      deploymentTarget:
        macOS: "14.0"

    settings:
      SWIFT_VERSION: "6.0"
      MACOSX_DEPLOYMENT_TARGET: "14.0"

    targets:
      MyApp:
        type: application
        platform: macOS
        sources:
          - MyApp
        settings:
          PRODUCT_BUNDLE_IDENTIFIER: com.company.myapp
          INFOPLIST_FILE: MyApp/Info.plist
          CODE_SIGN_ENTITLEMENTS: MyApp/MyApp.entitlements

      MyAppTests:
        type: bundle.unit-test
        platform: macOS
        sources:
          - MyAppTests
        dependencies:
          - target: MyApp
    ```

    ### After Editing project.yml
    ```bash
    xcodegen generate  # Regenerates .xcodeproj
    ```

    ---

    ## Instruments Profiling

    ### Common Templates
    | Template | Use Case |
    |----------|----------|
    | Time Profiler | CPU hotspots, slow methods |
    | Allocations | Memory leaks, retain cycles |
    | SwiftUI | View body evaluations, identity churn |
    | Core Animation | Offscreen renders, blending issues |
    | Network | HTTP timing, payload sizes |

    ### SwiftUI Profiling
    ```bash
    # Enable SwiftUI debugging (before launch)
    export SWIFTUI_VIEW_DEBUG=1

    # Or in scheme environment variables:
    # SWIFTUI_VIEW_DEBUG = 1
    ```

    ### Memory Graph
    1. Debug > Debug Memory Graph (while app running)
    2. Look for purple "!" icons (leaks)
    3. Filter by your module name
    4. Check for reference cycles

    ---

    ## Logging

    ### Unified Logging (Recommended)
    ```swift
    import os

    let logger = Logger(subsystem: "com.company.myapp", category: "general")
    logger.info("Started processing")
    logger.error("Failed: \\(error.localizedDescription)")
    ```

    ### Viewing Logs
    ```bash
    # Stream live
    log stream --predicate 'process == "MyApp"' --style compact

    # Show recent
    log show --predicate 'process == "MyApp"' --last 5m
    ```

    ---

    ## Testing

    ### Swift Testing (Modern)
    ```swift
    import Testing

    @Test func exampleTest() {
        #expect(2 + 2 == 4)
    }

    @Test("Async operation completes")
    func asyncTest() async {
        let result = await fetchData()
        #expect(result != nil)
    }
    ```

    ### Running Tests
    ```bash
    # Via project tools (recommended)
    ./Scripts/build.rb verify

    # Raw xcodebuild (avoid)
    xcodebuild -scheme MyApp -destination "platform=macOS" test
    ```

    ---

    ## Distribution

    ### Development (No Signing)
    - Build and run locally
    - No notarization needed

    ### Direct Distribution (Outside App Store)
    1. Sign with Developer ID Application certificate
    2. Enable Hardened Runtime
    3. Notarize with `xcrun notarytool`
    4. Staple ticket: `xcrun stapler staple MyApp.app`

    ### Notarization Commands
    ```bash
    # 1. Create ZIP for notarization
    ditto -c -k --keepParent MyApp.app MyApp.zip

    # 2. Submit for notarization
    xcrun notarytool submit MyApp.zip \\
        --apple-id "you@example.com" \\
        --team-id "TEAM123" \\
        --password "@keychain:AC_PASSWORD" \\
        --wait

    # 3. Staple the ticket
    xcrun stapler staple MyApp.app

    # 4. Verify
    spctl -a -vvv MyApp.app
    ```

    ### App Store
    1. Sign with Apple Distribution certificate
    2. Enable Sandboxing
    3. Archive and upload via Xcode or `xcrun altool`

    ---

    *Generated by SaneProcess mac_context (v2.0 - WWDC 2025)*
    *750+ lines of Mac-specific knowledge to keep your AI on the rails*
    *"Your AI Developer is drunk. Here is the Supervisor."*
  CONTEXT
end

# Main
FileUtils.mkdir_p(File.dirname(CONTEXT_FILE))
File.write(CONTEXT_FILE, generate_mac_context)

line_count = generate_mac_context.lines.count
puts '🍎 Mac Developer Context injected'
puts "   #{line_count} lines → #{CONTEXT_FILE}"
puts ''
puts '💡 Add to your CLAUDE.md:'
puts '   > Read .claude/mac_context.md before any Mac development work'
puts ''
puts '🚂 "Your AI Developer is drunk. Here is the Supervisor."'
